---

- name: "Create a temporary directory for job_logs"
  file:
    path: "/var/tmp/dci_{{ job_id }}_logs"
    state: directory
    mode: 0700
  register: job_logs

- name: "cnf-cert pre-run"
  include_role:
    name: cnf-cert
    tasks_from: pre-run.yml
  vars:
    tnf_git_dir: "{{ dci_cache_dir }}"
    tnf_registry: "{{ local_registry_host }}:{{ local_registry_port }}"
    tnf_registry_creds: "{{ local_registry_user }}:{{ local_registry_password }}"
  when: do_cnf_cert is defined and do_cnf_cert|bool

...
